# todo
scene_name = "10-layers"
out_file = 'F:\PBA\admm_soft\admm-elasticity\result\10-layers'
separate_out = false
show_windows = true

[global]
dt = 0.0333
pin = [0, 1, 2, 3]
g = 12.8
density = 0.1

[solver]

admm_max_iter = 25
DCD_interval = 5
GS_max_iter = 5
contact.use_CCD = true
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = true
contact.w_scale = 200.0
contact.kappa = 1e6
contact.beta = 0.5e5
contact.mu = 0.7
contact.unique = false
damp.kl = 1e-3
damp.km = 1e-4

[DCD]
narrow.max_collision = 40000
narrow.thickness = 0e-2
broad.radius = 1e-2
broad.strategy = 'rebuild'

[[mesh]]
f.path = 'flat/flat.obj'
f.type = 'tri'
f.color = 0
t.scale = 2.5
t.translate = [0, 0.8, 0]
t.rotate = [0, 0, 0]
k.stretch = 500.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1.0
k.use_limit = true

[[mesh]]
f.path = 'flat/flat.obj'
f.type = 'tri'
f.color = 1
t.scale = 2.0
t.translate = [0, 1.4, 0]
t.rotate = [0, 20, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1.0
k.use_limit = true


[[collider]]
type = 'plane'
center = [0, -2, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 10
color.background = [0.1, 0.1, 0.1]
enable_ground = false