scene_name = "grid"
# out_file = './'
out_file = 'F:\PBA\admm_soft\admm-elasticity\result\grid\'
separate_out = false
show_windows = true

[global]
dt = 0.033
# pin = [0, 19, 399]
# pin = [0, 19, 380]
pin = []
g = 2.98
# density = 10.0

[solver]
admm_max_iter = 30
DCD_interval = 10
GS_max_iter = 2
contact.use_CCD = true
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = true
contact.w_scale = 30
contact.kappa = 1e6
contact.beta = 1e5
contact.mu = 0.5
contact.unique = false
damp.kl = 1e-3
damp.km = 0

[DCD]
narrow.max_collision = 50000
narrow.thickness = 1e-2
broad.radius = 1e-2
broad.strategy = 'rebuild'


[[mesh]]
f.path = 'flat/grid_5x5.obj'
f.type = 'tri'
f.color = 18
t.scale = 2
t.translate = [0.4, 0.2, 0.1]
t.rotate = [0, 0, 0]
k.stretch = 1000.0
k.min_limit = 0.98
k.max_limit = 1.02
k.bending = 1
k.use_limit = true
density = 3.0

[[mesh]]
f.path = 'flat/grid_20x20.obj'
f.type = 'static'
f.color = 14
t.scale = 2
t.translate = [-1, 0, -1]
t.rotate = [30, 0, 0]
k.stretch = 1000.0
k.min_limit = 0.98
k.max_limit = 1.02
k.bending = 1
k.use_limit = false
density = 15.0
animate = ""

[mesh_post]
center_ids = []


[[collider]]
type = 'plane'
center = [0, -100, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 4
color.background = [0.1, 0.1, 0.1]
enable_ground = false