scene_name = "mat"
out_file = 'F:\PBA\admm_soft\admm-elasticity\result\mat'
seperate_out = false
show_windows = true

[global]
dt = 0.0333
# pin = [20, 39, 60, 79] # 20x20
# pin = [40, 159, 120, 79] # 40x40
pin = [] 
g = 0.98
density = 0.1

[solver]
admm_max_iter = 25
DCD_interval = 5
GS_max_iter = 10
contact.use_CCD = false
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = true
contact.w_scale = 1000.0
contact.kappa = 1e6
contact.beta = 3e5
contact.mu = 0.5
contact.unique = false

damp.kl = 1e-4
damp.km = 0

[DCD]
narrow.max_collision = 40000
narrow.thickness = 1e-2
broad.radius = 1e-2
broad.strategy = 'rebuild'

[[mesh]]
f.path = 'tetmesh/mat40x40.msh'
f.type = 'tet'
f.color = 0
t.scale = 4
t.translate = [0, 0.5, 0]
t.rotate = [10, 0, 0]
k.stretch = 10000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.use_limit = true

[[mesh]]
f.path = 'tetmesh/mat40x40.msh'
f.type = 'tet'
f.color = 0
t.scale = 4
t.translate = [0.2, 1.2, 0.2]
t.rotate = [20, 0, 0]
k.stretch = 10000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.use_limit = true

[mesh_post]
center_ids = []


[[collider]]
type = 'plane'
center = [0, 0, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 3
color.background = [0.1, 0.1, 0.1]
enable_ground = false

