scene_name = "10-layers-skew-mu005"
# out_file = './'
out_file = 'F:\PBA\admm_soft\admm-elasticity\result\10-layers-skew-mu005\'
separate_out = false
show_windows = true
GPU = false

[global]
dt = 0.025
pin = [0, 1, 2, 3]
g = 2.5
# density = 10.0

[solver]
# # for Jacobi
# admm_max_iter = 25
# DCD_interval = 5
# GS_max_iter = 15
# admm.warmstart_Ue = true
# admm.warmstart_Uc = true
# contact.enable = true
# contact.w_scale = 500.0
# contact.kappa = 1e6
# contact.beta = 0.1e5
# contact.mu = 0.1
# damp.kl = 1e-4
# damp.km = 0
# # for NNCG
admm_max_iter = 20
DCD_interval = 10
GS_max_iter = 5
Global_Jacobi_iter = 3
contact.use_CCD = false
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = true
contact.w_scale = 80.0
contact.kappa = 1e5
contact.beta = 1e5
contact.mu = 0.8
contact.unique = false
damp.kl = 1e-3
damp.km = 1e-4

[DCD]
narrow.max_collision = 80000
narrow.thickness = 6e-2
broad.radius = 6e-2
broad.strategy = 'rebuild'

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 0
t.scale = 2.5
t.translate = [0, 0.8, 0]
t.rotate = [10, 0, 0]
k.stretch = 15000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = false
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 1
t.scale = 2.0
t.translate = [0, 1.4, 0]
t.rotate = [0, 20, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 2
t.scale = 2.0
t.translate = [0, 1.8, 0]
t.rotate = [0, 40, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 3
t.scale = 2.0
t.translate = [0, 2.2, 0]
t.rotate = [0, 60, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 4
t.scale = 2.0
t.translate = [0, 2.6, 0]
t.rotate = [0, 80, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 5
t.scale = 2.0
t.translate = [0, 3.0, 0]
t.rotate = [0, 100, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 6
t.scale = 2.0
t.translate = [0, 3.4, 0]
t.rotate = [0, 120, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 7
t.scale = 2.0
t.translate = [0, 3.8, 0]
t.rotate = [0, 140, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 8
t.scale = 2.0
t.translate = [0, 4.2, 0]
t.rotate = [0, 160, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0

[[mesh]]
f.path = 'flat/flat_v651.obj'
f.type = 'tri'
f.color = 9
t.scale = 2.0
t.translate = [0, 4.6, 0]
t.rotate = [0, 180, 0]
k.stretch = 1000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 3.0
k.use_limit = true
density = 1.0


[[mesh]]
f.path = 'tetmesh/unitball-1287.msh'
f.type = 'tet'
f.color = 10
t.scale = 1.0
t.translate = [0, 5.8, 0]
t.rotate = [0, 0, 0]
k.stretch = 1500.0
k.min_limit = 0.99
k.max_limit = 1.01
k.use_limit = false
density = 10.0


[mesh_post]
center_ids = []

[[collider]]
type = 'plane'
center = [0, -2, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 10
color.background = [0.1, 0.1, 0.1]
enable_ground = false