scene_name = "fabric_2"
out_file = 'D:\data\padmm_result\fabric_2'
seperate_out = false
show_windows = true
GPU = true

[global]
dt = 0.01
pin = [0, 1, 2, 3]
g = 3.98

[solver]
admm_max_iter = 11
DCD_interval = 5
GS_max_iter = 10
Global_Jacobi_iter = 10
contact.use_CCD = false
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = false
contact.use_Jacobi = true
contact.w_scale = 15
contact.kappa = 1e5
contact.beta = 1e5
contact.unique = true
contact.use_heu_wc = false
contact.mu = 0.8
damp.kl = 1e-4
damp.km = 1e-3

[DCD]
narrow.max_collision = 200000
narrow.thickness = 3e-2
broad.radius = 3e-2
broad.strategy = 'rebuild'

# [[mesh]]
# f.path = 'flat/flat_v31389.obj'
# f.type = 'tri'
# f.color = 0
# t.scale = 15
# t.translate = [0, 0.8, 0]
# t.rotate = [0, 0, 0]
# k.stretch = 19000.0
# k.min_limit = 0.95
# k.max_limit = 1.05
# k.bending = 10.0
# k.use_limit = false
# density = 4.0

[[mesh]]
f.path = 'flat/flat_v10649.obj'
f.type = 'tri'
f.color = 0
t.scale = 3.5
t.translate = [0, 0.8, 0]
t.rotate = [0, 0, 0]
k.stretch = 19000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1000.1
k.use_limit = false
density = 4.0

[[mesh]]
f.path = 'flat/flat_v10649.obj'
f.type = 'tri'
f.color = 1
t.scale = 3.5
t.translate = [0, 1.8, 0]
t.rotate = [0, 30, 0]
k.stretch = 15000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1000.0
k.use_limit = false
density = 4.0

[[mesh]]
f.path = 'flat/flat_v10649.obj'
f.type = 'tri'
f.color = 2
t.scale = 3.5
t.translate = [0, 2.5, 0]
t.rotate = [0, 60, 0]
k.stretch = 15000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1.0
k.use_limit = false
density = 4.0

[[mesh]]
f.path = 'flat/flat_v10649.obj'
f.type = 'tri'
f.color = 3
t.scale = 3.5
t.translate = [0, 3.2, 0]
t.rotate = [0, 90, 0]
k.stretch = 15000.0
k.min_limit = 0.95
k.max_limit = 1.05
k.bending = 1000.0
k.use_limit = false
density = 4.0

# [[mesh]]
# f.path = 'flat/flat_v134.obj'
# f.type = 'tri'
# f.color = 3
# t.scale = 2.5
# t.translate = [0, 1.8, 0]
# t.rotate = [0, 45, 0]
# k.stretch = 15000.0
# k.min_limit = 0.95
# k.max_limit = 1.05
# k.bending = 1.0
# k.use_limit = false
# density = 4.0


[mesh_post]
center_ids = []

[[collider]]
type = 'plane'
center = [0, -2, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 10
color.background = [0.1, 0.1, 0.1]
enable_ground = false