scene_name = "wc_effect_heu"
out_file = 'C:\codebase\admm_elasticity\result\wc_effect_heu'
seperate_out = false
show_windows = true
end_frame = 1000
out_bin = true

[global]
dt = 0.02
pin = []
g = 2.98
# density = 10.0

[solver]
admm_max_iter = 24
DCD_interval = 5
GS_max_iter = 10
contact.use_CCD = true
admm.warmstart_Ue = true
admm.warmstart_Uc = true
contact.enable = true
contact.w_scale = 200.0
contact.kappa = 1e6
contact.unique = false
contact.beta = 1e5
contact.mu = 0.5
contact.use_heu_wc = false
contact.wc_beta = 25
contact.wc_sigma = 0.001
damp.kl = 0
damp.km = 0


[DCD]
narrow.max_collision = 400000
narrow.thickness = 1e-2
broad.radius = 1e-2
broad.strategy = 'rebuild'

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'static'
f.color = 1
t.scale = 4.0
t.translate = [0.0, 0.0, 0]
t.rotate = [0, 0, 0]
k.stretch = 8000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0
animate = ""

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'tri'
f.color = 6
t.scale = 4.0
t.translate = [0.0, 0.4, 0]
t.rotate = [0, 15, 0]
k.stretch = 15000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'tri'
f.color = 7
t.scale = 4.0
t.translate = [0.0, 0.8, 0]
t.rotate = [0, 30, 0]
k.stretch = 15000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'tri'
f.color = 8
t.scale = 4.0
t.translate = [0.0, 1.2, 0]
t.rotate = [0, 45, 0]
k.stretch = 15000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'tri'
f.color = 9
t.scale = 4.0
t.translate = [0.0, 1.6, 0]
t.rotate = [0, 60, 0]
k.stretch = 15000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0

[[mesh]]
f.path = 'trimesh\square3K.obj'
f.type = 'tri'
f.color = 10
t.scale = 4.0
t.translate = [0.0, 2.0, 0]
t.rotate = [0, 75, 0]
k.stretch = 15000.0
k.min_limit = 0.999
k.max_limit = 1.001
k.bending = 0.0005
# k.use_limit = true
k.use_limit = false
density = 1.0


[mesh_post]
center_ids = []

[[collider]]
type = 'plane'
center = [0, -2, 0]
halfside = 5.0
normal = [0, 1, 0]

[viewer]
scale = 5
color.background = [0.1, 0.1, 0.1]
enable_ground = false